### PR TITLE
Made all playbooks, roles consistent 

### PR DESCRIPTION
**Pull request by DanyC97**
by adding `---` and removing empty lines.

Next time i might look into adding ansible-lint so we make sure all playbooks/ roles follow same rules (easy to follow when everything is consistent )

### CODE REVIEW

**Comment by DanyC97** [comment]
@dav1x @cooktheryan  fyi, cosmetic changes, minimal impact

**Comment by cooktheryan** [comment]
Excellent stuffy @DanyC97

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
going to re-fire ci testing later on. No reason why this should have failed

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by dav1x** [comment]
LGTM

**Pull request merged**
