### PR TITLE
add node fix due to playbook movement

### PR DESCRIPTION
**Pull request by cooktheryan**
This is a fix due to some playbooks being moved. This will serve as the generic starting point for adding nodes within AWS and with other providers

### CODE REVIEW

**Comment by detiber** [comment]
@cooktheryan yamllint errors from travis.

**Comment by cooktheryan** [comment]
Cool ill fix. Attempted to write code too late in the day

**Comment by detiber** [comment]
@cooktheryan late in the day is the best time for me, fewer distractions :)

**Comment by cooktheryan** [comment]
Learned a lesson in committing too close

**Pull request merged**
