### PR TITLE
handle ec2 classic accounts better

### PR DESCRIPTION
**Pull request by detiber**
Resolves: #56

### CODE REVIEW

**Comment by cooktheryan** [comment]
@detiber i tried to launch with the new script and hit 

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{ lookup('ec2_zones_by_region', region) }}: Could not lookup zones for region: us-east-1\nexception: 'VPC' object has no attribute 'isDefault'"}
```
same for west

````
fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{ lookup('ec2_zones_by_region', region) }}: Could not lookup zones for region: us-west-2\nexception: 'VPC' object has no attribute 'isDefault'"}
````

**Comment by detiber** [comment]
@cooktheryan that's what I get for testing in a repl rather than the actual filter...  fix incoming

**Comment by detiber** [comment]
@cooktheryan mind trying again?

**Comment by cooktheryan** [comment]
@detiber testing now

**Comment by cooktheryan** [comment]
Tested against us-east-1 with success! Excellent work @detiber :+1:

**Pull request merged**
