### PR TITLE
GCP: Add --scaleup flag to gcloud.sh

### PR DESCRIPTION
**Pull request by bdurrow**

### CODE REVIEW

**Comment by bdurrow** [comment]
These commits are also included in https://github.com/openshift/openshift-ansible-contrib/pull/509

**Comment by Fale** [comment]
Should this PR be rebased due to #547 ?

**Comment by pschiffe** [comment]
No need to rebase, I'm afraid that just including the scaleup playbooks won't be enough to properly scale up the cluster (I mean the script should also resize instance groups as necessary). I'll be looking into it soon.

**Comment by bdurrow** [comment]
@pschiffe, The following line specifically adjusts the instance groups per the config.yaml:
```
ansible-playbook -e @../config.yaml $@ playbooks/core-infra.yaml
```

**Comment by pschiffe** [comment]
Ah, right. Sorry, I didn't have the chance, to look at it properly..

**Comment by pschiffe** [comment]
Resubmitted as #598

**Pull request closed without merging**
