### PR TITLE
the fedora/25-cloud-base box is avaliable.

### PR DESCRIPTION
**Pull request by warmchang**
check the "https://atlas.hashicorp.com/fedora/boxes/25-cloud-base/".

### CODE REVIEW

**Comment by cooktheryan** [comment]
@detiber do we have someone familiar with Vagrant that can +1 this?

**Comment by detiber** [comment]
@cgwalters @dustymabe are either of you able to verify this change?

**Comment by cgwalters** [comment]
I haven't tested it, but makes sense to me.

**Comment by cgwalters** [comment]
The cloud base box is the yum managed, non-Atomic Host variant.

**Comment by dustymabe** [comment]
@detiber - I don't have a setup for that right now. if @warmchang says it works then I say merge it.

**Pull request merged**
