### PR TITLE
VMware - Add the log_path into ansible.cfg

### LINKED ISSUE #215: VMware - add the log_path into ansible.cfg
Is easier for debug to have a known ansible log location

### PR DESCRIPTION
**Pull request by DanyC97**
Fixes #215

### CODE REVIEW

**Comment by cooktheryan** [comment]
I definitely agree about the importance of the log but I worry about the privileges required to write to /var/log

**Comment by dav1x** [comment]
@DanyC97 lets add the ansible.log to the .gitignore and do it locally instead? This way we can still execute the installation as a non root user

**Comment by DanyC97** [comment]
@dav1x okay, i don't mind the location as long as it logs. Anyone can change the location if it doesn't work for them. will update the PR in few min

cheers

**Comment by DanyC97** [comment]
@dav1x as requested, PR updated, cheers

**Comment by dav1x** [comment]
LGTM

**Pull request merged**
