### PR TITLE
Fix Flannel SDN setup for openstack provider

### PR DESCRIPTION
**Pull request by bogdando**
#### What does this PR do?

* Gather facts on app nodes to fix the expiration of cached facts
* Use better names for custom iptables rules for Flannel
* Remove OSEv3 specific pre-flight checks from the common checks

#### How should this be manually tested?
A trivial change, no tests needed.

#### Is there a relevant Issue open for this?
Provide a link to any open issues that describe the problem you are solving.

#### Who would you like to review this?
cc: @tomassedovic @e-minguez  PTAL

### CODE REVIEW

**Comment by e-minguez** [comment]
LGTM, did you tested it?

**Comment by bogdando** [comment]
@e-minguez nope, the change is trivial

**Comment by bogdando** [comment]
@tomassedovic could you  please approve?

**Comment by bogdando** [comment]
@tomassedovic the CI failure looks unrelated (it seems broken)

```
TASK [template_service_broker : Reconcile with RBAC file] **********************
Monday 13 November 2017  09:54:02 +0000 (0:00:00.867)       0:15:11.186 ******* 
fatal: [master-0.openshift-1826.example.com]: FAILED! => {"changed": true, "cmd": "oc process -f \"/tmp/tsb-ansible-ZBdtjG/rbac-template.yaml\" | oc auth reconcile -f -", "delta": "0:00:00.400961", "end": "2017-11-13 09:54:02.967483", "failed": true, "rc": 1, "start": "2017-11-13 09:54:02.566522", "stderr": "Error: unknown shorthand flag: 'f' in -f\n\n\nUsage:\n  oc auth [options]\n\nAvailable Commands:\n  can-i       Check whether an action is allowed\n\nUse \"oc <command> --help\" for more information about a given command.\nUse \"oc options\" for a list of global command-line options (applies to all commands).", "stderr_lines": ["Error: unknown shorthand flag: 'f' in -f", "", "", "Usage:", "  oc auth [options]", "", "Available Commands:", "  can-i       Check whether an action is allowed", "", "Use \"oc <command> --help\" for more information about a given command.", "Use \"oc options\" for a list of global command-line options (applies to all commands)."], "stdout": "", "stdout_lines": []}
```

**Pull request merged**
