### PR TITLE
Gce fix

### PR DESCRIPTION
**Pull request by cooktheryan**
Selinux GCE fix. I believe the error is occurring due to an issue with the iso on access.redhat.com.

Also added option to state whether the RHEL image should or should not be removed at the time up --revert

### CODE REVIEW

**Comment by cooktheryan** [comment]
Validation of functionality
```
PLAY RECAP *********************************************************************
localhost                  : ok=23   changed=16   unreachable=0    failed=0   
ocp-infra-bbn9             : ok=164  changed=58   unreachable=0    failed=0   
ocp-infra-bz93             : ok=164  changed=58   unreachable=0    failed=0   
ocp-master-5d91            : ok=532  changed=175  unreachable=0    failed=0   
ocp-master-jwv1            : ok=341  changed=117  unreachable=0    failed=0   
ocp-master-wktv            : ok=341  changed=117  unreachable=0    failed=0   
ocp-node-f7s4              : ok=157  changed=61   unreachable=0    failed=0   
ocp-node-ql6d              : ok=157  changed=61   unreachable=0    failed=0   

Connection to 35.185.0.200 closed.

Deployment is complete. OpenShift Console can be found at https://master.gce-validate.sysdeseng.com
```

**Comment by cooktheryan** [comment]
[BUG: GCE cannot launch pods](https://trello.com/c/LVegfHZU/559-bug-gce-cannot-launch-pods)

**Comment by cooktheryan** [comment]
[BUG: GCE cannot launch pods](https://trello.com/c/LVegfHZU/559-bug-gce-cannot-launch-pods)

**Comment by themurph** [comment]
LGTM, I tried just adding the docker_selinux package to the hosts but that did not fix the selinux issue. This method is the best way to ensure that the installation does not get hung up on a selinux permissions error.

+1
Merging

**Pull request merged**
