### PR TITLE
Allow users to launch clusters based on CentOS and Openshift Origin

### PR DESCRIPTION
**Pull request by bdurrow**

### CODE REVIEW

**Comment by bdurrow** [comment]
Changes include:
  - Method of building gold image based on public gce image
  - Skipping Subscription Manager setup in the gold image
  - Add repo for openshift related rpms
  - Add additional packages to gold image that are required for successful deployment

**Comment by bdurrow** [comment]
Patch will likely need to be reviewed by @pschiffe.

**Comment by pschiffe** [comment]
Thanks for the PR. We definitely want to support centos and origin, and I will try to evaluate your PR as soon as possible.

**Comment by pschiffe** [comment]
Merged slightly different version in #483

**Pull request closed without merging**
