### PR TITLE
Adding the option to use 'stack_state' to allow for easy de-provisioning

### PR DESCRIPTION
**Pull request by oybed**
#### What does this PR do?
Submitting a role to allow for easy openstack/heat stack deletion

#### How should this be manually tested?
Read README + use the `test.yml` playbook in the `tests` directory

#### Is there a relevant Issue open for this?
N/A

#### Who would you like to review this?
cc: @tomassedovic @bogdando

### CODE REVIEW

**Comment by oybed** [comment]
@etsauer yeah, we can do that, but that means restructuring the `main.yml` to avoid a messy set of checks around generating the heat templates, etc. I figured it would be cleaner to keep it separate. Let me work it and see how it goes.

**Comment by oybed** [comment]
@bogdando @cooktheryan @tomassedovic Please let us know what we need to do to get this one merged. We'd like to cut another release to have a stable starting point, but would like to include this one + PR https://github.com/openshift/openshift-ansible-contrib/pull/769 in this release.

**Comment by tomassedovic** [comment]
Sorry @oybed! I've started the end to end test, feel free to merge this when it passes (or I'll do it tomorrow)

**Comment by etsauer** [comment]
All checks have passed. Going to go ahead and merge

**Pull request merged**
