### PR TITLE
3.4 release

### PR DESCRIPTION
**Pull request by cooktheryan**

### CODE REVIEW

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by rafabene** [comment]
Shouldn't this variable be changed as well? https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/gce-cli/config.sh.example#L38

**Comment by cooktheryan** [comment]
Excellent find @rafabene

**Comment by rafabene** [comment]
When this PR will be merged? I want to try 3.4 and apply this PR to my local checkout, but it seems that the repo is cloned again (without the changes).

**Comment by cooktheryan** [comment]
Really hoping for tomorrow/monday. We are working out one last GCE item
before shipping.

**Comment by dav1x** [comment]
shipit

**Pull request merged**
