### PR TITLE
openstack: make server ports be trunk ports

### PR DESCRIPTION
**Pull request by celebdor**
This ensures that the ports that the servers were using before this
commit will be parent ports of Neutron trunk ports. Thanks to this,
there can be nested Neutron ports inside the OS::NOva::Server resources
created either in the heat stack or dynamically inside the Instances.

Signed-off-by: Antoni Segura Puimedon <antonisp@celebdor.com>

#### What does this PR do?
Makes cluster VM ports be parent ports. This means that subports can be created inside the VMs that can run isolated from the parent port at no extra encapsulation cost.

#### How should this be manually tested?

First let's create a new net/subnet with two ports
`
openstack network create yellow
openstack subnet create --network yellow submarine
openstack port create --network yellow --fixed-ip subnet=submarine port
openstack port create --network yellow --fixed-ip subnet=submarine starboard
`
Then let's make them subports:
`
openstack network trunk set --subport port=port,segmentation-type=vlan,segmentation-id=10 id_of_the_vm_trunk
openstack network trunk set --subport port=starboard,segmentation-type=vlan,segmentation-id=11 id_of_the_vm_trunk
`
Check and write down the ip addresses assigned to **port** and to **starboard**

Then, on a single server that has a trunk port set as the 'eth0' device
`
sudo ip link add link eth0 name port type vlan id 10
sudo ip netns add babor
sudo ip link set netns babor dev port
sudo ip netns exec babor ip addr add address_we_got_when_creating_port dev port
 
sudo ip link add link eth0 name starboard type vlan id 11
sudo ip netns add estribor
sudo ip link set netns estribor dev starboard
sudo ip netns exec estribor ip addr add address_we_got_when_creating_starboard dev starboard
`
Finally we test connectivity:
`
sudo ip netns exec estribor ping address_we_got_when_creating_port
`
The ping should succeed.

#### Is there a relevant Issue open for this?
Provide a link to any open issues that describe the problem you are solving.

#### Who would you like to review this?
cc: @tomassedovic @bogdando PTAL

### CODE REVIEW

**Comment by celebdor** [comment]
Still need to test it. I just managed to run a similar heat template in tripleo pike, so I figured I'd submit before I forget.

**Comment by tomassedovic** [comment]
I'll try to give it a test soonish. Since this always uses trunk ports now, is there any disadvantage or potential breakage to that? Or are we always safe to use them even when they're not needed?

Also, I still haven't fully figured out what's going on with our CI so merging might be slow :-(

**Comment by tomassedovic** [comment]
@celebdor I've tried to follow the steps on a devstack setup with trunking and ovs firewall enabled, but no matter what I do, the final ping results in:

```
$ sudo ip netns exec estribor ping 192.168.139.3
connect: Network is unreachable
```

That said, your changes look very reasonable and they won't change the default installation, so I'm happy to chalk this up to an incorrect setup or me messing up the instructions and just merge this.

Of course once we start adding a proper kuryr integration, that will need more documentation and testing.

**Comment by tomassedovic** [comment]
I've triggered an end to end CI run here to make sure this doesn't break anything:

https://travis-ci.org/openshift/openshift-ansible-contrib/builds/272836049

When that passes, we can merge it (but I don't have high hopes because Heat has been acting up all week)

**Comment by tomassedovic** [comment]
Hm, this needed to merge with the latest master to work. I've triggered an end-end CI here and it passed:

https://travis-ci.org/openshift/openshift-ansible-contrib/builds/274505688

I'll merge this.

**Pull request merged**
