### PR TITLE
Update openshift_release in the sample inventory

### PR DESCRIPTION
**Pull request by tomassedovic**
#### What does this PR do?
Openshift Enterprise is now at 3.6. And we should not specify the
origin release as it's more rolling and the older versions may no longer
be available (this has broken our CI recently).

#### How should this be manually tested?
Do an end to end deployment of origin and enterprise using the sample inventory. Nothing should break.

#### Is there a relevant Issue open for this?
n/a

#### Who would you like to review this?
cc: @Tlacenka  @bogdando @tzumainn  PTAL

### CODE REVIEW

**Comment by tomassedovic** [comment]
@bogdando sure, will do. As far as I can tell, it uses the latest release of origin (which used to be 1.5.1 but is 3.6.0). But it looks like the configured origin repos only provide the latest version, so when origin makes a new release, the old one is not available anymore.

**Comment by tomassedovic** [comment]
done

**Comment by tomassedovic** [comment]
Please ignore the failed push check -- I accidentally pushed a branch into this repo which triggered a check that I then cancelled.

**Comment by Tlacenka** [comment]
@tomassedovic I noticed that in the provisioning [README](https://github.com/openshift/openshift-ansible-contrib/blob/master/playbooks/provisioning/openstack/README.md), it still requires origin release. I think it would be nice to update the documentation of `OSEv3.yml`.

**Comment by tomassedovic** [comment]
Good point, thanks!

**Comment by Tlacenka** [comment]
@tomassedovic 
I might be missing something but when trying to do the end to end development, it fails in the OpenShift installation part. I am using `rhel73` image for the nodes.

```
Message:  You requested openshift_release 3.6, which is not matched by
               the latest OpenShift RPM we detected as atomic-openshift-3.5.5.31
               on host master-0.openshift.example.com.
               We will only install the latest RPMs, so please ensure you are getting the release
               you expect. You may need to adjust your Ansible inventory, modify the repositories
               available on the host, or run the appropriate OpenShift upgrade playbook.
```

**Pull request merged**
