### PR TITLE
testing patching the system to resolve sub-manager errors

### PR DESCRIPTION
**Pull request by cooktheryan**
Consistently hitting an error with subscription manager. Going to test to see if updating packages resolves.

```
13:11:32 TASK [rhsm-subscription : Register host] ***************************************
13:11:45 fatal: [ose-infra-node01.ci.sysdeseng.com]: FAILED! => {
13:11:45     "changed": false, 
13:11:45     "cmd": "subscription-manager list --available", 
13:11:45     "failed": true, 
13:11:45     "rc": 70
13:11:45 }
13:11:45 
13:11:45 STDERR:
13:11:45 
13:11:45 Unable to verify server's identity: (104, 'Connection reset by peer')
```

### CODE REVIEW

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
This is weird. Works when manually ran on system but through ci the subscription-manager repos --disable=* fails

**Comment by detiber** [comment]
@cooktheryan is it doing some type of glob matching that is causing an issue on the jenkins host? Maybe there needs to be quoting or escaping used.

**Comment by cooktheryan** [comment]
This is the error im getting in the logs

```
16:17:23 STDOUT:
16:17:23 
16:17:23 Error: '*' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
16:17:23 fatal: [ose-master02.ci.sysdeseng.com]: FAILED! => {
16:17:23     "changed": true, 
16:17:23     "cmd": [
16:17:23         "subscription-manager", 
16:17:23         "repos", 
16:17:23         "--disable=*"
16:17:23     ], 
16:17:23     "delta": "0:00:05.196201", 
16:17:23     "end": "2017-01-31 16:17:22.887529", 
16:17:23     "failed": true, 
16:17:23     "rc": 1, 
16:17:23     "start": "2017-01-31 16:17:17.691328", 
16:17:23     "warnings": []
16:17:23 }
```

**Comment by detiber** [comment]
@cooktheryan wonder if you are hitting a bug in a particular version of subscription-manager or the subscription isn't showing any repos enabled?

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
There is definitely something weird going on when running through CI right now. For some reason the servers aren't even getting subscribed

```
[root@ip-10-20-5-23 ~]# subscription-manager list 

+-------------------------------------------+
    Installed Product Status
+-------------------------------------------+
Product Name:   Red Hat Enterprise Linux Server
Product ID:     69
Version:        7.3
Arch:           x86_64
Status:         Not Subscribed
Status Details: Not supported by a valid subscription.
Starts:         
Ends: 
```

**Comment by dav1x** [comment]
I was getting the same. Sometimes it works. Sometimes not. Maybe rhn issues?

Davis

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
Merging the playbook but it is not required for AWS to successfully register. Problems occur due to lack of valid subscriptions

**Pull request merged**
