### PR TITLE
Azure logging metrics and logging deployment in post installation step

### PR DESCRIPTION
**Pull request by e-minguez**
#### What does this PR do?
* Optionally deploys OCP metrics by setting a parameter in the ARM template or the ansible vars (true by default)
* Metrics components are deployed as 1 cassandra, 1 hawkular-metrics and 1 heapster pod (enough for 25000 pods[1])
* Cassandra uses a PV dedicated (xfs azure disk)
* Optionally deploys OCP logging by setting a parameter in the ARM template or the ansible vars (true by default) and OPS logging as well (false by default)
* Logging architecture is 1 fluentd pod (daemonset) on each host (including masters), 3 elasticsearch pods, 2 kibana and 1 curator for HA (specially the elasticsearch)
* OPS logging same architecture
* Dedicated 10Gb PV for every elasticsearch pod
* HA and disk size is easily configurable using variables in bastion.sh
* `enable-controller-attach-detach': ['true']` parameter as it looks like it is the proper way (and it will be by default in next releases[2])
* Renamed storage accounts with a proper naming
* Proper order in nodes labels (like masters or infranodes)
* Fix for hosts to be able to DNS resolve without using the full domainname
* Registry console node selector to be deployed in the infranodes instead regular ones

#### How should this be manually tested?
Run the installation using ansible or the Azure portal with the metrics, logging and ops logging parameters to "true" and after installation, check logging, ops logging and metrics pods, it should look like:

```
$ oc get pods --all-namespaces -o wide
NAMESPACE         NAME                              READY     STATUS    RESTARTS   AGE       IP            NODE
asdf              guestbook-1-1dj2v                 1/1       Running   0          49m       10.129.2.5    node01
asdf              guestbook-1-lmbcb                 1/1       Running   0          49m       10.128.4.4    node02
asdf              guestbook-1-wk6gz                 1/1       Running   0          49m       10.131.2.5    node03
default           docker-registry-2-5wblb           1/1       Running   0          1h        10.130.0.4    infranode3
default           registry-console-2-cb5mn          1/1       Running   0          1h        10.128.0.2    infranode1
default           router-1-6kmdn                    1/1       Running   0          1h        10.0.2.4      infranode2
default           router-1-qxj23                    1/1       Running   0          1h        10.0.2.5      infranode3
default           router-1-xsvb3                    1/1       Running   0          1h        10.0.2.6      infranode1
logging           logging-curator-1-z9khd           1/1       Running   4          58m       10.128.0.13   infranode1
logging           logging-curator-ops-1-j2sxm       1/1       Running   5          58m       10.128.2.11   infranode2
logging           logging-es-0usf83ay-1-nlsz8       1/1       Running   7          58m       10.128.0.16   infranode1
logging           logging-es-690ebmic-1-kt4sl       1/1       Running   7          58m       10.128.2.12   infranode2
logging           logging-es-ops-b44n3gav-1-zkl3r   1/1       Running   7          58m       10.128.0.17   infranode1
logging           logging-es-ops-j7n7g1rw-1-wrw14   1/1       Running   7          58m       10.130.0.10   infranode3
logging           logging-es-ops-xlzj28qv-1-hc10k   1/1       Running   7          58m       10.128.2.13   infranode2
logging           logging-es-r58jbl8f-1-s6zn1       1/1       Running   7          58m       10.130.0.9    infranode3
logging           logging-fluentd-19fg0             1/1       Running   0          57m       10.131.2.3    node03
logging           logging-fluentd-1nxgn             1/1       Running   0          58m       10.131.0.3    master2
logging           logging-fluentd-355kc             1/1       Running   0          57m       10.128.4.3    node02
logging           logging-fluentd-5twkg             1/1       Running   0          57m       10.129.0.3    master3
logging           logging-fluentd-blmmm             1/1       Running   0          57m       10.130.2.3    master1
logging           logging-fluentd-cjzj1             1/1       Running   0          57m       10.128.0.15   infranode1
logging           logging-fluentd-g5jqw             1/1       Running   0          58m       10.130.0.8    infranode3
logging           logging-fluentd-nb62x             1/1       Running   0          58m       10.129.2.4    node01
logging           logging-fluentd-rn0xc             1/1       Running   0          58m       10.128.2.10   infranode2
logging           logging-kibana-1-1m90g            2/2       Running   0          58m       10.128.0.12   infranode1
logging           logging-kibana-ops-1-1w11q        2/2       Running   0          58m       10.128.0.14   infranode1
openshift-infra   hawkular-cassandra-1-h9mrq        1/1       Running   0          1h        10.130.0.6    infranode3
openshift-infra   hawkular-metrics-7scbw            1/1       Running   0          1h        10.128.2.5    infranode2
openshift-infra   heapster-32xhg                    1/1       Running   0          1h        10.130.0.5    infranode3
```

#### Is there a relevant Issue open for this?

* Lots of Azure issues[3][4][5][6] made me go for the post-installation steps instead for an "out-of-the-box" experience
* Logging doesn't work right now because of this bug[3], but editing the configmap fixes it

#### Who would you like to review this?
cc: @glennswest  @cooktheryan 

[1] https://docs.openshift.com/container-platform/3.5/scaling_performance/scaling_cluster_metrics.html#cluster-metrics-scaling-openshift-metrics-pods
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1467970#c6
[3] https://bugzilla.redhat.com/show_bug.cgi?id=1467970
[4] https://bugzilla.redhat.com/show_bug.cgi?id=1467575
[5] https://bugzilla.redhat.com/show_bug.cgi?id=1469001
[6] https://bugzilla.redhat.com/show_bug.cgi?id=1467966
[7] https://bugzilla.redhat.com/show_bug.cgi?id=1466626

### CODE REVIEW

**Comment by cooktheryan** [comment]
I'm good with this. @glennswest Ill let you review

**Comment by glennswest** [comment]
So with the PR:
Normal Deployment works fine, with logging off?
Can we discuss the overhead of the deployment in "Memory" and "CPU" on the hosts?
I think its something people will ask.

**Comment by e-minguez** [comment]
Regarding Memory and CPU, this is the current status of the cluster:

```
[edu@bastion ~]$ oc adm top node --heapster-namespace='openshift-infra'  --heapster-scheme="https"
NAME         CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%   
infranode3   372m         9%        4657Mi          33%       
master3      68m          1%        1923Mi          13%       
node02       43m          1%        1437Mi          5%        
infranode1   145m         3%        4139Mi          29%       
master2      57m          1%        1522Mi          10%       
infranode2   167m         4%        4419Mi          31%       
master1      68m          1%        1726Mi          12%       
node03       38m          0%        1395Mi          4%        
node01       43m          1%        1400Mi          4%        
[edu@bastion ~]$ oc adm top pod --heapster-namespace='openshift-infra'  --heapster-scheme="https" --all-namespaces
NAMESPACE         NAME                                   CPU(cores)   MEMORY(bytes)   
openshift-infra   hawkular-cassandra-1-h9mrq             161m         1423Mi          
logging           logging-fluentd-g5jqw                  8m           92Mi            
logging           logging-es-ops-b44n3gav-1-zkl3r        19m          861Mi           
logging           logging-fluentd-rn0xc                  6m           86Mi            
logging           logging-es-ops-xlzj28qv-1-hc10k        23m          720Mi           
logging           logging-fluentd-1nxgn                  5m           87Mi            
logging           logging-fluentd-cjzj1                  5m           94Mi            
logging           logging-fluentd-blmmm                  7m           92Mi            
asdf              guestbook-1-lmbcb                      0m           0Mi             
ocp-ops-view      kube-ops-view-619735142-zv658          0m           37Mi            
logging           logging-es-0usf83ay-1-nlsz8            9m           675Mi           
openshift-infra   heapster-32xhg                         4m           48Mi            
default           router-1-xsvb3                         2m           33Mi            
logging           logging-kibana-ops-1-1w11q             21m          495Mi           
logging           logging-fluentd-nb62x                  4m           79Mi            
logging           logging-curator-ops-1-j2sxm            0m           19Mi            
logging           logging-es-ops-j7n7g1rw-1-wrw14        31m          863Mi           
openshift-infra   hawkular-metrics-7scbw                 57m          1455Mi          
logging           logging-es-r58jbl8f-1-s6zn1            10m          713Mi           
logging           logging-fluentd-19fg0                  4m           81Mi            
asdf              guestbook-1-1dj2v                      0m           2Mi             
ocp-ops-view      kube-ops-view-redis-3698144219-x9kz6   0m           6Mi             
default           router-1-6kmdn                         2m           32Mi            
logging           logging-kibana-1-1m90g                 20m          551Mi           
logging           logging-curator-1-z9khd                0m           21Mi            
default           docker-registry-2-5wblb                1m           12Mi            
default           registry-console-2-cb5mn               0m           5Mi             
logging           logging-fluentd-355kc                  5m           81Mi            
default           router-1-qxj23                         2m           33Mi            
logging           logging-es-690ebmic-1-kt4sl            13m          696Mi           
logging           logging-fluentd-5twkg                  10m          120Mi           
asdf              guestbook-1-wk6gz                      0m           0Mi 
```

All components are deployed in the infranodes so they shouldn't affect the app nodes themselves...
I'm going to redeploy without metrics nor logging.
Thanks.

**Comment by e-minguez** [comment]
Without metrics nor logging, like a charm:

```
[edu@bastion ~]$ oc get pods --all-namespaces -o wide
NAMESPACE   NAME                       READY     STATUS    RESTARTS   AGE       IP           NODE
default     docker-registry-2-q20g7    1/1       Running   0          2m        10.128.4.4   infranode3
default     registry-console-2-gpd5r   1/1       Running   0          3m        10.130.0.3   infranode2
default     router-1-742t2             1/1       Running   0          4m        10.0.2.4     infranode1
default     router-1-lt9jm             1/1       Running   0          4m        10.0.2.6     infranode2
default     router-1-rgq93             1/1       Running   0          4m        10.0.2.5     infranode3
[edu@bastion ~]$ cat openshift-postinstall.out 
storageclass "generic" created
```

**Comment by e-minguez** [comment]
Added a new commit due to this https://bugzilla.redhat.com/show_bug.cgi?id=1454666#c1

**Pull request merged**
