### PR TITLE
Add ansibledeployocp to support ansible deployment of arm template

### PR DESCRIPTION
**Pull request by glennswest**
Add scripts to support deployment of the Azure OCP Reference architecture from ansible.

### CODE REVIEW

**Comment by e-minguez** [comment]
Regarding the test playbook, I'd say to rework it as it contains a few hardcoded values (I didn't have the chance to do it)

**Comment by glennswest** [comment]
Rename it as example ?

**Comment by e-minguez** [comment]
Ok to me (and create a card to follow up the testing and don't forget about it)

**Comment by glennswest** [comment]
Actually the testing had a card 
I use the script with the test every run as well

**Pull request merged**
