### PR TITLE
Don't reattach the pool

### PR DESCRIPTION
**Pull request by pschiffe**
#### What does this PR do?
Don't reattach the pool if already attached during the registration.

#### How should this be manually tested?
Verify that deployment successfully finishes.

#### Who would you like to review this?
cc: @cooktheryan PTAL

### CODE REVIEW

**Comment by pschiffe** [comment]
aos-ci-test

**Comment by pschiffe** [comment]
aos-ci-test

**Comment by pschiffe** [comment]
@cooktheryan can you please check this out? GCP ref. arch. doesn't work because of this :(

**Comment by cooktheryan** [comment]
verifying now. Will merge as soon as i can

**Pull request merged**
