### PR TITLE
intial commit of static inventory creation

### PR DESCRIPTION
**Pull request by cooktheryan**
Initial pull request for static inventory creation in GCE

### CODE REVIEW

**Comment by cooktheryan** [comment]
Will fix lint errors in the morning

**Comment by cooktheryan** [comment]
@themurph can I get a review of this?

**Comment by detiber** [comment]
not really a huge fan of the static inventory, any reason we couldn't use a dynamic inventory?

**Comment by cooktheryan** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1417315

**Comment by detiber** [comment]
arrgh, okay...  I suppose it is a necessary evil for now

**Comment by cooktheryan** [comment]
@pschiffe or @themurph can I get a +1 on this so I can begin documenting how to run for the bugzilla

**Comment by cooktheryan** [comment]
[BUG: Support requires a static inventory](https://trello.com/c/lnaCZjHN/604-bug-support-requires-a-static-inventory)

**Pull request merged**
