### PR TITLE
[WIP] Removed emptydir & unified variables per provider

### PR DESCRIPTION
**Pull request by e-minguez**

### CODE REVIEW

**Comment by pschiffe** [comment]
aos-ci-test

**Comment by e-minguez** [comment]
My bad... it is "vars_fileS" instead "vars_file" :disappointed:

**Comment by e-minguez** [comment]
aos-ci-test

**Comment by e-minguez** [comment]
My bad (again)... it looks like the error was pretty descriptive:
```'vars_files' is not a valid attribute for a PlaybookInclude``` so I've used include_vars it in a specific tasks before the include...

**Comment by e-minguez** [comment]
aos-ci-test

**Comment by cooktheryan** [comment]
aos-ci-test

**Comment by e-minguez** [comment]
aos-ci-test

**Comment by e-minguez** [comment]
aos-ci-test

**Comment by e-minguez** [comment]
aos-ci-test

**Comment by e-minguez** [comment]
aos-ci-test

**Comment by e-minguez** [comment]
aos-ci-test

**Comment by e-minguez** [comment]
This is becoming a messy PR... I'll close it once working and I promise it would be cleaner.

**Comment by e-minguez** [comment]
Connection reset by peer... aos-ci-test

**Comment by cooktheryan** [comment]
It looks like subscriptions may be maxed out which would be part of our issue. I'll run this through ci this afternoon up cleaning up

**Comment by e-minguez** [comment]
Trying again!

**Comment by e-minguez** [comment]
aos-ci-test

**Comment by pschiffe** [comment]
So, what about this PR? Kill it?

**Comment by e-minguez** [comment]
Kill it with fire.

**Pull request closed without merging**
