### PR TITLE
RHV High-availability code

### PR DESCRIPTION
**Pull request by cwilkers**
#### What does this PR do?
Enables VMs to be highly available in RHV and establishes negative affinity to keep masters and infra off the same host if possible.

#### How should this be manually tested?
Run ovirt-vm-infra.yaml

#### Is there a relevant Issue open for this?
Part of design.

#### Who would you like to review this?
cc: @cooktheryan

### CODE REVIEW

**Comment by cooktheryan** [comment]
@cwilkers Ill leave it up to you if you want to merge. Just depends what you want to do with that storage setting

**Comment by cwilkers** [comment]
@cooktheryan I would like to update once more with the storage setup once I blow everything away again and retest.

**Comment by cooktheryan** [comment]
Sounds good. I'll remove the approval

**Comment by cwilkers** [comment]
@cooktheryan I think this PR is complete. If I need another PR with networking fixes, it should go in separately.

**Pull request merged**
