### PR TITLE
GCP: Refactor data disk(s) creation and setup to instance template

### PR DESCRIPTION
**Pull request by bdurrow**
This work brings the GCP deployment closer to instances groups launched instances being functional.  It also supports a ./gcloud.sh --scaleup target I'm working on.

### CODE REVIEW

**Comment by bdurrow** [comment]
Travis found a whitespace problem.  I ammended the commit that introduced the errant whitespace and rewrote history on the Pull Request branch. The branch in my fork reflects the change but the PR still shows the old commit.  I’m not sure how to get this updated and trigger travis again.

**Comment by bdurrow** [comment]
All commits here are included in https://github.com/openshift/openshift-ansible-contrib/pull/508.

**Comment by pschiffe** [comment]
I'm testing this PR, but the cloud init doesn't work for me (on RHEL-7):
```
Jul  4 18:42:42 ocp-peter-infra-node-vntp cloud-init: 2017-07-04 18:42:38,779 - __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: '# cloud-config\nwrite_fil...'
```
Did you see such error in your testing?

**Comment by bdurrow** [comment]
I didn't recall seeing that error.  I did have some trouble at first but I didn't take notes as to what that trouble was because I considered it resolved when I finally got it working.

Will you check the other flavors and see if you have the same problem with all of them or just the infra nodes?

**Comment by pschiffe** [comment]
It's all nodes, cloud-init version in RHEL is:
```
$ rpm -q cloud-init
cloud-init-0.7.6-2.el7.x86_64
```

I'll check centos.

**Comment by pschiffe** [comment]
I see the same error on centos, cloud-init version is:
```
$ rpm -q cloud-init
cloud-init-0.7.5-10.el7.centos.1.x86_64
```
I will investigate further.

**Comment by bdurrow** [comment]
I retested in that branch but couldn't reproduce the problem.  Will you provide the same output for your test?
[brad@gca-dev-00-builder gce-cli]$ git rev-parse --verify HEAD
2e8e91fa7d9563023f9070d4145c5366707da322
[brad@gca-dev-00-builder gce-cli]$ gcloud compute instances describe master-infra-node-9wq9
<SNIP>
metadata:
  fingerprint: W_nZjHXR9kc=
  items:
  - key: user-data
    value: |
      #cloud-config
      write_files:
      - content: |
          DEVS="/dev/disk/by-id/google-docker"
          VG="docker-vol"
          DATA_SIZE="95%VG"
          EXTRA_DOCKER_STORAGE_OPTIONS="--storage-opt dm.basesize=3G"
        path: /etc/sysconfig/docker-storage-setup
        permissions: '0644'

      fs_setup:
         - label: osl
           filesystem: xfs
           device: /dev/disk/by-id/google-openshift
           partition: none

      mounts:
        - [ '/dev/disk/by-id/google-openshift', '/var/lib/origin/openshift.local.volumes', 'xfs', 'gquota', '0', '0' ]
  - key: instance-template
    value: projects/<<REDACTED>>/global/instanceTemplates/master-infra-node-template
  - key: created-by
    value: projects/<<REDACTED>>/regions/us-central1/instanceGroupManagers/master-infra-node
  kind: compute#metadata
<SNIP>
[brad@gca-dev-00-builder gce-cli]$ ssh master-infra-node-9wq9
The authenticity of host 'master-infra-node-9wq9 (<no hostip for proxy command>)' can't be established.
ECDSA key fingerprint is 63:61:cd:e1:50:23:e7:2b:40:69:67:91:c1:5d:ac:63.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'master-infra-node-9wq9' (ECDSA) to the list of known hosts.
Last login: Fri Jun 30 21:24:16 2017 from 116.84.154.104.bc.googleusercontent.com
[cloud-user@master-infra-node-9wq9 ~]$ cat /var/log/cloud-init.log
Jul  7 12:47:01 master-infra-node-9wq9 cloud-init: Cloud-init v. 0.7.5 running 'init-local' at Fri, 07 Jul 2017 12:47:01 +0000. Up 9.19 seconds.
Jul  7 12:47:08 master-infra-node-9wq9 cloud-init: Cloud-init v. 0.7.5 running 'init' at Fri, 07 Jul 2017 12:47:08 +0000. Up 15.86 seconds.
Jul  7 12:47:10 master-infra-node-9wq9 cloud-init: ci-info: +++++++++++++++++++++++++++Net device info+++++++++++++++++++++++++++
Jul  7 12:47:10 master-infra-node-9wq9 cloud-init: ci-info: +--------+------+-------------+-----------------+-------------------+
Jul  7 12:47:11 master-infra-node-9wq9 cloud-init: ci-info: | Device |  Up  |   Address   |       Mask      |     Hw-Address    |
Jul  7 12:47:11 master-infra-node-9wq9 cloud-init: ci-info: +--------+------+-------------+-----------------+-------------------+
Jul  7 12:47:11 master-infra-node-9wq9 cloud-init: ci-info: |  lo:   | True |  127.0.0.1  |    255.0.0.0    |         .         |
Jul  7 12:47:12 master-infra-node-9wq9 cloud-init: ci-info: | eth0:  | True | 10.128.0.10 | 255.255.255.255 | 42:01:0a:80:00:0a |
Jul  7 12:47:12 master-infra-node-9wq9 cloud-init: ci-info: +--------+------+-------------+-----------------+-------------------+
Jul  7 12:47:12 master-infra-node-9wq9 cloud-init: ci-info: ++++++++++++++++++++++++++++++++++Route info++++++++++++++++++++++++++++++++++
Jul  7 12:47:13 master-infra-node-9wq9 cloud-init: ci-info: +-------+-----------------+------------+-----------------+-----------+-------+
Jul  7 12:47:13 master-infra-node-9wq9 cloud-init: ci-info: | Route |   Destination   |  Gateway   |     Genmask     | Interface | Flags |
Jul  7 12:47:13 master-infra-node-9wq9 cloud-init: ci-info: +-------+-----------------+------------+-----------------+-----------+-------+
Jul  7 12:47:13 master-infra-node-9wq9 cloud-init: ci-info: |   0   |     0.0.0.0     | 10.128.0.1 |     0.0.0.0     |    eth0   |   UG  |
Jul  7 12:47:14 master-infra-node-9wq9 cloud-init: ci-info: |   1   |    10.128.0.1   |  0.0.0.0   | 255.255.255.255 |    eth0   |   UH  |
Jul  7 12:47:14 master-infra-node-9wq9 cloud-init: ci-info: |   2   |   10.128.0.10   |  0.0.0.0   | 255.255.255.255 |    eth0   |   UH  |
Jul  7 12:47:14 master-infra-node-9wq9 cloud-init: ci-info: |   3   | 169.254.169.254 | 10.128.0.1 | 255.255.255.255 |    eth0   |  UGH  |
Jul  7 12:47:14 master-infra-node-9wq9 cloud-init: ci-info: +-------+-----------------+------------+-----------------+-----------+-------+
Jul  7 12:47:15 master-infra-node-9wq9 cloud-init: Cloud-init v. 0.7.5 running 'modules:config' at Fri, 07 Jul 2017 12:47:14 +0000. Up 21.71 seconds.
Jul  7 12:47:16 master-infra-node-9wq9 cloud-init: Cloud-init v. 0.7.5 running 'modules:final' at Fri, 07 Jul 2017 12:47:15 +0000. Up 22.84 seconds.
Jul  7 12:47:16 master-infra-node-9wq9 cloud-init: Cloud-init v. 0.7.5 finished at Fri, 07 Jul 2017 12:47:16 +0000. Datasource DataSourceGCE.  Up 23.41 seconds
[cloud-user@master-infra-node-9wq9 ~]$ cat /var/log/cloud-init-output.log
Cloud-init v. 0.7.5 running 'init-local' at Fri, 07 Jul 2017 12:47:01 +0000. Up 9.19 seconds.
Cloud-init v. 0.7.5 running 'init' at Fri, 07 Jul 2017 12:47:08 +0000. Up 15.86 seconds.
ci-info: +++++++++++++++++++++++++++Net device info+++++++++++++++++++++++++++
ci-info: +--------+------+-------------+-----------------+-------------------+
ci-info: | Device |  Up  |   Address   |       Mask      |     Hw-Address    |
ci-info: +--------+------+-------------+-----------------+-------------------+
ci-info: |  lo:   | True |  127.0.0.1  |    255.0.0.0    |         .         |
ci-info: | eth0:  | True | 10.128.0.10 | 255.255.255.255 | 42:01:0a:80:00:0a |
ci-info: +--------+------+-------------+-----------------+-------------------+
ci-info: ++++++++++++++++++++++++++++++++++Route info++++++++++++++++++++++++++++++++++
ci-info: +-------+-----------------+------------+-----------------+-----------+-------+
ci-info: | Route |   Destination   |  Gateway   |     Genmask     | Interface | Flags |
ci-info: +-------+-----------------+------------+-----------------+-----------+-------+
ci-info: |   0   |     0.0.0.0     | 10.128.0.1 |     0.0.0.0     |    eth0   |   UG  |
ci-info: |   1   |    10.128.0.1   |  0.0.0.0   | 255.255.255.255 |    eth0   |   UH  |
ci-info: |   2   |   10.128.0.10   |  0.0.0.0   | 255.255.255.255 |    eth0   |   UH  |
ci-info: |   3   | 169.254.169.254 | 10.128.0.1 | 255.255.255.255 |    eth0   |  UGH  |
ci-info: +-------+-----------------+------------+-----------------+-----------+-------+
Cloud-init v. 0.7.5 running 'modules:config' at Fri, 07 Jul 2017 12:47:14 +0000. Up 21.71 seconds.
Cloud-init v. 0.7.5 running 'modules:final' at Fri, 07 Jul 2017 12:47:15 +0000. Up 22.84 seconds.
Cloud-init v. 0.7.5 finished at Fri, 07 Jul 2017 12:47:16 +0000. Datasource DataSourceGCE.  Up 23.41 seconds

**Comment by pschiffe** [comment]
Hi @bdurrow , thanks for the info, I was able to resolve the issue. I already did some modifications to the PR :-) most of them are just cosmetics, but the cloud-init needs the empty lines between `write_files`, `fs_setup`, etc, otherwise it throws that error.

Anyway, I have another problem now:
```
TASK [openshift_node_certificates : fail] ****************************************************************
task path: /home/pschiffe/work/redhat/e2e/openshift-ansible/roles/openshift_node_certificates/tasks/main.yml:9
fatal: [ocp-peter-infra-node-hqzq]: FAILED! => {"changed": false, "failed": true, "msg": "CA certificate /etc/origin/master/ca.crt doesn't exist on CA host ocp-peter-master-x29s. Apply 'openshift_ca' role to ocp-peter-master-x29s.\n"}
```

and it's somehow related to this PR, because the deployment from master branch runs just fine. So if you have any ideas, please let me know. The instances seem to be working fine, with additional disks successfully attached. The error above is occurring to me with both, `origin` and `enterprise` deployments.

**Comment by bdurrow** [comment]
I have only see this happen when the originally elected "single master" host is either unavailable or possibly was chosen differently in a subsequent run.  I don't think that it is specific to this branch.  Have you seen it more than once?

**Comment by pschiffe** [comment]
@bdurrow actually yes, every-time I've tried this PR (maybe 5 times or so), and never without this PR. I know that it seems unrelated, but..

**Comment by bdurrow** [comment]
To be clear, you have tried to ./gcloud.sh --revert first and you still get this error?  I will look at the diffs from master and try to figure it out.  It doesn't happen to me.

**Comment by bdurrow** [comment]
Will you add the ansible-playbook summary to the error message you provided above?

**Comment by pschiffe** [comment]
@bdurrow sure, I'm doing `./gcloud.sh --teardown && ./gcloud.sh -vv` Summary is:
```
TASK [openshift_node_certificates : Ensure CA certificate exists on openshift_ca_host] *******************
task path: /home/pschiffe/work/redhat/e2e/openshift-ansible/roles/openshift_node_certificates/tasks/main.yml:2
ok: [ocp-peter-infra-node-hqzq -> None] => {"changed": false, "stat": {"exists": false}}

TASK [openshift_node_certificates : fail] ****************************************************************
task path: /home/pschiffe/work/redhat/e2e/openshift-ansible/roles/openshift_node_certificates/tasks/main.yml:9
fatal: [ocp-peter-infra-node-hqzq]: FAILED! => {"changed": false, "failed": true, "msg": "CA certificate /etc/origin/master/ca.crt doesn't exist on CA host ocp-peter-master-x29s. Apply 'openshift_ca' role to ocp-peter-master-x29s.\n"}

NO MORE HOSTS LEFT ***************************************************************************************

PLAY RECAP ***********************************************************************************************
localhost                  : ok=42   changed=18   unreachable=0    failed=0   
ocp-peter-bastion          : ok=2    changed=0    unreachable=0    failed=0   
ocp-peter-infra-node-1fgs  : ok=0    changed=0    unreachable=1    failed=0   
ocp-peter-infra-node-hqzq  : ok=149  changed=36   unreachable=0    failed=1   
ocp-peter-infra-node-vkr0  : ok=0    changed=0    unreachable=1    failed=0   
ocp-peter-master-2c97      : ok=0    changed=0    unreachable=1    failed=0   
ocp-peter-master-981x      : ok=0    changed=0    unreachable=1    failed=0   
ocp-peter-master-x29s      : ok=149  changed=47   unreachable=0    failed=1   
ocp-peter-node-dq89        : ok=147  changed=36   unreachable=0    failed=0   
ocp-peter-node-jbz5        : ok=0    changed=0    unreachable=1    failed=0   
ocp-peter-tmp-instance     : ok=10   changed=8    unreachable=0    failed=0
```

And now I see there are `unreachable` hosts, but they are reachable via ssh and working.. Maybe there are delays because of cloud-init? That doesn't seem probable..

**Comment by pschiffe** [comment]
@bdurrow ah, this is the real error, the other one is just a consequence:
```
TASK [etcd : Write etcd global config file] **************************************************************
task path: /home/pschiffe/work/redhat/e2e/openshift-ansible/roles/etcd/tasks/main.yml:123
fatal: [ocp-peter-master-x29s]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'etcd_hostname'"}
```

**Comment by bdurrow** [comment]
Thanks that makes the problem more clear.  There are multiple unreachable failures.  I made an attempt to get ansible to wait for all of the nodes but my play there has some kind of logic error.  I don't know the best way to handle this.  Running again without the revert resolves the problem.  I have a slightly better version that I can commit but it exits instead of continuing and we rung ./gcloud.sh again.  It is a timing issue but it isn't that it takes longer for the VMs to launch it is that we aren't attaching disks so we get to the next check that can mark a host as unreachable sooner.

Here is the version I am using now.  Would you like me to commit that to the branch?  I could also add a 60 second delay and that would work but it seems pretty lame:
```
#Ansible bug keeps this from working through the bastion host
#https://github.com/ansible/ansible/issues/23774
#- hosts: all
#  gather_facts: no
#  tasks:
#  - name: wait for instances to become available
#    wait_for_connection:
#      timeout: 900
- name: wait for instances to become available for ssh
  hosts: 'tag_{{ prefix}}-bastion:tag_{{ prefix }}'
  serial: 1
  gather_facts: no
  tasks:
  - name: ping hosts
    action: ping
    register: ping_result
    until: ping_result|succeeded
    retries: 120
    delay: 1
    ignore_errors: yes
  - name: reset unreachable hosts
    meta: clear_host_errors
```

**Comment by pschiffe** [comment]
@bdurrow on the second run of `gcloud.sh` it works, so it will be something with unprepared instances. No need to update the PR, I'll fix it tomorrow, it's too late for me today. Thanks!

**Comment by pschiffe** [comment]
Updated PR #537 - @bdurrow please take a look.
Anyway - awesome job, thanks for your contributions!

**Pull request closed without merging**
