### PR TITLE
Document global DNS security options

### PR DESCRIPTION
**Pull request by bogdando**
#### What does this PR do?
Depends on https://github.com/redhat-cop/infra-ansible/pull/69

* Document global DNS security options, specifically a recursion switches.
* Do not create a view if externally managed.
* Allow to specify the recursion settings for public/private views defined by the dns-view role.

note: dnsses is yet to be supported

#### How should this be manually tested?
Defaults are left as is and need no to be tested.
A secure setup recommended in the guide, should be tested:

* Define inventory vars:
  ```
  named_config_recursion: 'no'
  named_config_views:
    public:
      - recursion: 'no'
      ... (remaining data for the infra-ansible casl dns role) ...
  ```
* Provision a non-recursive public DNS, by [casl dns* roles](https://github.com/redhat-cop/infra-ansible/tree/master/roles/dns-server), using the inventory vars defined above. See this [example playbook](https://github.com/bogdando/ocp-inventory/blob/master/playbooks/deploy-dns-casl.yaml) based on the [osp 10 ref arch DNS service](https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/osp-dns) 'hacked' to use the infra-ansible casl dns role.
* Provision and deploy a mixed DNS servers setup, having an in-stack private DNS allowing recursion.
* e2e shall pass
* Verify there is no recursion available for the external DNS:
```
dig foo.com @<IP>
WARNING: recursion requested but not available
```
* Repeat the steps with an in-stack DNS server used for priv/pub views, and define `named_public_recursion: 'no'`.

#### Is there a relevant Issue open for this?
Related https://github.com/openshift/openshift-ansible-contrib/issues/621

#### Who would you like to review this?
cc: @tomassedovic @oybed PTAL

### CODE REVIEW

**Comment by bogdando** [comment]
dnssec options will not take effect yet, the dns-server role needs to be adjusted for required dnssec configuration steps, keys generating signing zones et al. But what is unexpected, I can see the dig tool showing `ra rd` flags and executes recursions against my test server, even though I told it to not recurse.

**Comment by oybed** [comment]
@bogdando keep in mind that the views also have recursion config - did you ensure those are disabled? In general, this needs better documentation, but you need to set:
```
named_config_views:
  - recursion: "no"
```

**Comment by oybed** [comment]
@bogdando as discussed, one enhancement we can make is to make the views default to the global setting rather than just default to enabled. I'll submit another PR to `infra-ansible` for this.

**Comment by bogdando** [comment]
@tomassedovic  it's ready for review and testing

**Comment by tomassedovic** [comment]
This looks great, thanks!

We need to sort out the default values (they're currently not working), but when I set them up explicitly:

```
named_public_recursion: 'no'
named_private_recursion: 'yes'
```

I've encountered two issues.

1. My openstack requires setting explicit forwarders (via `public_dns_nameservers`) and we currently only set those for the public views, not the private ones. That means the nodes could not install packages or do any external name resolutions.

Here's the views file on the deployed DNS:

```
$ ansible --become --private-key ~/.ssh/openshift -i devbox-inventory/ dns -m command -a 'cat /etc/named/named.conf.view'
dns-0.openshift.example.com | SUCCESS | rc=0 >>
view "private" {
        match-clients { "private"; };

        recursion yes;

        zone "openshift.example.com" IN {
                type master;
                file "static/private-openshift.example.com.db";
                allow-update { key private-openshift.example.com; };
        };


        zone "." {
                type forward;
                forwarders {
                        127.0.0.1;
                };
        };

};

view "public" {
        match-clients { "public"; };

        recursion no;

        zone "openshift.example.com" IN {
                type master;
                file "static/public-openshift.example.com.db";
                allow-update { key public-openshift.example.com; };
        };


        include "/etc/named.rfc1912.zones";

        zone "." {
                type forward;
                forwarders {
                        10.44.6.1;
                        10.44.6.2;
                        };
        };

};
```

That should be fixed by adding `forwarder: "{{ public_dns_nameservers }}"` to the private view here just like the public one does in our `dns-views` role:

https://github.com/openshift/openshift-ansible-contrib/blob/a9ca2ec9ec25e752dab2be543b91ddd122826057/roles/dns-views/tasks/main.yml#L9

Paging @oybed to make sure this actually makes sense.


2. When I did the above, the openshift-ansible installation succeeded, but running a build failed, because the build pod couldn't resolve names either.

I am not yet sure why this is and will investigate this further soon.

**Comment by bogdando** [comment]
@tomassedovic I think you're right and we need to

> That should be fixed by adding forwarder: "{{ public_dns_nameservers }}" to the private view

I'll test with the empty `public_dns_nameservers`. which is a default value, as well

**Comment by bogdando** [comment]
@tomassedovic basically, if we leave the default `public_dns_nameservers` empty, adding `forwarder: "{{ public_dns_nameservers }}"` to the private view would fix nothing

**Comment by tomassedovic** [comment]
But there are situations (such as the RDO Cloud) where empty `public_dns_nameservers` work already. These wouldn't be broken if we added an empty forwarder list to the private view would they?

I think the defaults should stay the same, but we should document the forwarders situation better. I'd prefer we didn't use any open DNS as a default, because they may be blocked in certain orgs and it would be difficult to debug that failure.

But we can say something like "if you're unsure what to put in here, you can try the google or opendns servers, but note that some organizations may be blocking them).

**Comment by bogdando** [comment]
@tomassedovic done

**Comment by tomassedovic** [comment]
Looks good, thanks! I'll test this once I've handled the CI issues (hopefully later today).

**Pull request merged**
