### PR TITLE
Allow installation of OCP 3.9 on GCP

### PR DESCRIPTION
**Pull request by agno01**
As OCP 3.9 is already released this commit updates the major version
from 7 to 9 and related variables and paths from the
config.yaml.example file for reference architecture built on GCP.

Some review and modifications to other reference architectures'
playbooks/roles might be needed.

This particular commit contains changes needed only to get it working
on GCP.

Only the deployment of fresh OpenShift cluster was tested by:

$ cd reference-architecture/gcp
$ ./ocp-on-gcp.sh -Dv -f 3

This worked w/o any issues when using all the defaults for GCP
deployment.

- increase openshift_major_version to 9
- fix path for the openshift-ansible installation playbook
- use openshift-ansible prerequisites playbook
- add openshift_facts playbook to gce ref arch inst playbook
- fix library path to point to lib_utils role in openshift-ansible
- fix metrics & logging related installation variables
- add GCP cloud provider multizone configuration
- add GCP cloud provider vars (prefix & project)
- change openshift.common.is_atomic to openshift_is_atomic conditions

cc: @tomassedovic @vrutkovs @ekuric PTAL

### CODE REVIEW

**Comment by agno01** [comment]
Could anyone please review and test this PR? It's hanging here for a while now... Thanks.

**Comment by cooktheryan** [comment]
@agno01 check out the latest reference architecture document for GCE

**Comment by agno01** [comment]
@cooktheryan do you mean this one?
https://access.redhat.com/documentation/en-us/reference_architectures/2018/html-single/deploying_and_managing_openshift_3.9_on_google_cloud_platform/
If yes, it doesn't mention anything about this particular repo and ansible playbooks & scripts used for deploying the underlying infra in GCP. Please correct me if you meant something else.

**Comment by cooktheryan** [comment]
Yes that is correct. The new reference architecture provides cli based
commands that will deploy a cluster. This helps to remove some of the
"what's going on?" around the deployment.

**Comment by agno01** [comment]
@cooktheryan OK, gotcha, however, the purpose of this PR is to make these ansible playbooks work with 3.9 as some paths has changed in openshift-ansible installer. So the question is whether or not someone is going to review this PR or not?

**Comment by agno01** [comment]
Apparently this PR does not make sense anymore as the 3.9 is being deployed other way. Closing.

**Pull request closed without merging**
