### PR TITLE
Move OCP variables to one place

### PR DESCRIPTION
**Pull request by pschiffe**
#### What does this PR do?
Moves OCP variables to one place.

#### How should this be manually tested?
Verify that the deployment finished successfully.

#### Is there a relevant Issue open for this?
PR #506

#### Who would you like to review this?
cc: @bdurrow @e-minguez @cooktheryan PTAL

### CODE REVIEW

**Comment by e-minguez** [comment]
👏 that's what I wanted to do [here](https://github.com/openshift/openshift-ansible-contrib/pull/365/files) but I failed every time. It would be nice to have the same approach on every other provider 🤔

**Comment by cooktheryan** [comment]
@e-minguez its like we almost just had this discussion :D

**Comment by pschiffe** [comment]
@e-minguez yeah, ansible sometimes just sucks.. I think that this solution is stupid, but it's probably the only one which works..

**Comment by bdurrow** [comment]
I think that this opens the possibility replace having the variables spelled out in the static-inventory template also.  I'm not sure a simple pattern matching would be enough but I imagine there is a robust YAML->JSON conversion method.

**Comment by pschiffe** [comment]
If you find something reasonable, just let me know. I don't know any better way how to do it now, and I just don't want to throw time at it as current state is fine.

**Pull request merged**
