### PR TITLE
Add ISSUE/PR github templates

### PR DESCRIPTION
**Pull request by bogdando**
Signed-off-by: Bogdan Dobrelya <bdobreli@redhat.com>

### CODE REVIEW

**Comment by bogdando** [comment]
@tomassedovic

**Comment by tomassedovic** [comment]
Pinging @cooktheryan (please add anyone else who might have a feedback on this, Ryan!).

I like the PR template (seems to come from casl-ansible and I really love their "how should this be tested" idea).

But the issues one feels incredibly heavy-handed and not necessarily providing a lot of benefit.

Also note that there's a lot of different work going into this repository (for gce, aws, vmware, scripts etc. related to the various reference architectures, etc.) so for a lot of the issues here things like Ansible or Shade are not applicable whatsoever.

**Comment by bogdando** [comment]
@cooktheryan PTAL ^^

**Comment by cooktheryan** [comment]
@bogdando and @tomassedovic I am ok with this as sometimes things that come in are sometimes closer to feature requests than issues. I +1 this

**Pull request merged**
